/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package khangtl.ui;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import khangtl.daos.StocksDAO;
import khangtl.dtos.StocksDTO;

/**
 *
 * @author Peter
 */
public class Parent extends javax.swing.JFrame {

    // Initialize global variables
    Object stockHeader[] = new Object[5];
    Object stockData[] = new Object[5];
    ArrayList<StocksDTO> stockList = new ArrayList<>();
    Child childScreen = new Child();

    /**
     * Creates new form Main
     */
    public Parent() throws Exception {
        initComponents();
        // Popup confirm dialog before exit program
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                int close = JOptionPane.showConfirmDialog(null, "Do you want to close program?", "", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
                if (close == JOptionPane.YES_OPTION) {
                    if (childScreen.isVisible()) {
                        childScreen.dispose();
                    }
                    e.getWindow().dispose();
                    System.exit(0);
                }
            }
        });

        // Add header of stock
        stockHeader[0] = "StockID";
        stockHeader[1] = "StockName";
        stockHeader[2] = "Address";
        stockHeader[3] = "DateAvailable";
        stockHeader[4] = "Note";

        updateData();
    }

    public void updateData() throws Exception {
        StocksDAO stockDAO = new StocksDAO();
        stockDAO.fetchStocks();
        stockList = stockDAO.getStocks();
        DefaultTableModel stockModel;
        stockModel = (DefaultTableModel) this.stockTbl.getModel();
        stockModel.setRowCount(0);
        stockModel.setColumnIdentifiers(stockHeader);
        // Add stock data to array
        for (int i = 0; i < stockList.size(); i++) {
            stockData[0] = stockList.get(i).getId();
            stockData[1] = stockList.get(i).getName();
            stockData[2] = stockList.get(i).getAddress();
            stockData[3] = stockList.get(i).getDateAvailable();
            stockData[3] = formatDate((Date) stockData[3]);
            stockData[4] = stockList.get(i).getNote();
            stockModel.addRow(stockData);
            stockModel.getDataVector().elementAt(i);
        }
        stockTbl.updateUI();
        if (stockList == null) {
            JOptionPane.showMessageDialog(this, "Your data is empty");
        }
    }

    public String formatDate(Date oldDate) throws ParseException {
        // Format Date Object to new format
        String pattern = "dd/MM/yyyy";
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat(pattern);

        String date = simpleDateFormat.format(oldDate);
        return date;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        stockTbl = new javax.swing.JTable();
        openBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(750, 250));
        setResizable(false);

        stockTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "StockID", "StockName", "Address", "DateAvailable", "Note"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(stockTbl);

        openBtn.setText("Open Item");
        openBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(openBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(openBtn)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openBtnActionPerformed
        // TODO add your handling code here:
        // Check unselect item
        int selectedRow = stockTbl.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select item");
            return;
        }
        StocksDTO dto = stockList.get(selectedRow);
        if (!childScreen.isVisible()) {
            // Passing data to children screen
            childScreen.data = dto;
            try {
                childScreen.setupData();
            } catch (Exception ex) {
                Logger.getLogger(Parent.class.getName()).log(Level.SEVERE, null, ex);
            }
            childScreen.setVisible(true);
        }
    }//GEN-LAST:event_openBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Parent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Parent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Parent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Parent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Parent().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Parent.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton openBtn;
    private javax.swing.JTable stockTbl;
    // End of variables declaration//GEN-END:variables
}
