/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package khangtl.ui;

import java.awt.Color;

/**
 *
 * @author Peter
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        radioGroup.add(radioRed);
        radioRed.setActionCommand("Red");
        radioGroup.add(radioBlue);
        radioBlue.setActionCommand("Blue");
        radioGroup.add(radioGreen);
        radioGreen.setActionCommand("Green");
        radioGroup.add(radioBlack);
        radioBlack.setActionCommand("Black");
        radioRed.setSelected(true);
        txtColor.setText(radioGroup.getSelection().getActionCommand());
        txtColor.setBackground(Color.red);
        txtColor.setOpaque(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioGroup = new javax.swing.ButtonGroup();
        radioRed = new javax.swing.JRadioButton();
        radioBlue = new javax.swing.JRadioButton();
        radioGreen = new javax.swing.JRadioButton();
        radioBlack = new javax.swing.JRadioButton();
        txtColor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(700, 350));

        radioRed.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radioRed.setText("Red");
        radioRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRedActionPerformed(evt);
            }
        });

        radioBlue.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radioBlue.setText("Blue");
        radioBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBlueActionPerformed(evt);
            }
        });

        radioGreen.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radioGreen.setText("Green");
        radioGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioGreenActionPerformed(evt);
            }
        });

        radioBlack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radioBlack.setText("Black");
        radioBlack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBlackActionPerformed(evt);
            }
        });

        txtColor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtColor.setForeground(new java.awt.Color(255, 255, 255));
        txtColor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtColor.setText("Color");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioRed)
                    .addComponent(radioBlue)
                    .addComponent(radioGreen)
                    .addComponent(radioBlack))
                .addContainerGap(56, Short.MAX_VALUE))
            .addComponent(txtColor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioRed)
                .addGap(18, 18, 18)
                .addComponent(radioBlue)
                .addGap(18, 18, 18)
                .addComponent(radioGreen)
                .addGap(18, 18, 18)
                .addComponent(radioBlack)
                .addGap(18, 18, 18)
                .addComponent(txtColor, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioBlackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBlackActionPerformed
        // TODO add your handling code here:
        radioBlack.setSelected(true);
        txtColor.setText(radioGroup.getSelection().getActionCommand());
        txtColor.setBackground(Color.black);
        txtColor.setOpaque(true);
    }//GEN-LAST:event_radioBlackActionPerformed

    private void radioGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioGreenActionPerformed
        // TODO add your handling code here:
        radioGreen.setSelected(true);
        txtColor.setText(radioGroup.getSelection().getActionCommand());
        txtColor.setBackground(Color.green);
        txtColor.setOpaque(true);
    }//GEN-LAST:event_radioGreenActionPerformed

    private void radioBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBlueActionPerformed
        // TODO add your handling code here:
        radioBlue.setSelected(true);
        txtColor.setText(radioGroup.getSelection().getActionCommand());
        txtColor.setBackground(Color.blue);
        txtColor.setOpaque(true);
    }//GEN-LAST:event_radioBlueActionPerformed

    private void radioRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRedActionPerformed
        // TODO add your handling code here:
        radioRed.setSelected(true);
        txtColor.setText(radioGroup.getSelection().getActionCommand());
        txtColor.setBackground(Color.red);
        txtColor.setOpaque(true);
    }//GEN-LAST:event_radioRedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton radioBlack;
    private javax.swing.JRadioButton radioBlue;
    private javax.swing.JRadioButton radioGreen;
    private javax.swing.ButtonGroup radioGroup;
    private javax.swing.JRadioButton radioRed;
    private javax.swing.JLabel txtColor;
    // End of variables declaration//GEN-END:variables
}
