/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package khangtl.ui;

import khangtl.methods.ImageTool;

/**
 *
 * @author Peter
 */
public class ImageIcon extends javax.swing.JFrame {

    javax.swing.ImageIcon firstImage = ImageTool.createImageByPath("src/assets/images/bird.jpg");
    javax.swing.ImageIcon secondImage = ImageTool.createImageByPath("src/assets/images/cat.jpg");
    javax.swing.ImageIcon thirdImage = ImageTool.createImageByPath("src/assets/images/dog.jpg");
    javax.swing.ImageIcon fourthImage = ImageTool.createImageByPath("src/assets/images/pig.jpg");

    /**
     * Creates new form ImageIcon
     */
    public ImageIcon() {
        initComponents();
        mainLbl.setIcon(ImageTool.scaleImage(firstImage, mainLbl.getSize().width, mainLbl.getSize().height));
        firstBtn.setIcon(ImageTool.scaleImage(firstImage, firstBtn.getSize().width - 10, firstBtn.getSize().height - 10));
        secondBtn.setIcon(ImageTool.scaleImage(secondImage, secondBtn.getSize().width - 10, secondBtn.getSize().height - 10));
        thirdBtn.setIcon(ImageTool.scaleImage(thirdImage, thirdBtn.getSize().width - 10, thirdBtn.getSize().height - 10));
        fourthBtn.setIcon(ImageTool.scaleImage(fourthImage, fourthBtn.getSize().width - 10, fourthBtn.getSize().height - 10));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        thirdBtn = new javax.swing.JButton();
        firstBtn = new javax.swing.JButton();
        secondBtn = new javax.swing.JButton();
        fourthBtn = new javax.swing.JButton();
        mainLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(550, 300));
        setResizable(false);

        thirdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thirdBtnActionPerformed(evt);
            }
        });

        firstBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstBtnActionPerformed(evt);
            }
        });

        secondBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondBtnActionPerformed(evt);
            }
        });

        fourthBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourthBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(firstBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(secondBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(thirdBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fourthBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(mainLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(mainLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(thirdBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fourthBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secondBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstBtnActionPerformed
        // TODO add your handling code here:
        mainLbl.setIcon(ImageTool.scaleImage(firstImage, mainLbl.getSize().width, mainLbl.getSize().height));
    }//GEN-LAST:event_firstBtnActionPerformed

    private void secondBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondBtnActionPerformed
        // TODO add your handling code here:
        mainLbl.setIcon(ImageTool.scaleImage(secondImage, mainLbl.getSize().width, mainLbl.getSize().height));
    }//GEN-LAST:event_secondBtnActionPerformed

    private void thirdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thirdBtnActionPerformed
        // TODO add your handling code here:
        mainLbl.setIcon(ImageTool.scaleImage(thirdImage, mainLbl.getSize().width, mainLbl.getSize().height));
    }//GEN-LAST:event_thirdBtnActionPerformed

    private void fourthBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourthBtnActionPerformed
        // TODO add your handling code here:
        mainLbl.setIcon(ImageTool.scaleImage(fourthImage, mainLbl.getSize().width, mainLbl.getSize().height));
    }//GEN-LAST:event_fourthBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImageIcon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImageIcon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImageIcon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImageIcon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImageIcon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton firstBtn;
    private javax.swing.JButton fourthBtn;
    private javax.swing.JLabel mainLbl;
    private javax.swing.JButton secondBtn;
    private javax.swing.JButton thirdBtn;
    // End of variables declaration//GEN-END:variables
}
